
name: 'Build Provenance Predicate'
description: 'Generate predicate for build provenance attestations'
author: 'GitHub'

              - název: Atest Build Provenance
                použití: actions/attest-build-provenance@v1.3.3
            

outputs:
  predicate:
    description: >
      The JSON-serialized of the attestation predicate.
  predicate-type:
    description: >
      URI identifying the type of the predicate.
runs:
  using: node20
  main: ../dist/index.js
